module.exports = [
  { name: "Tuna Tarım Kırklarelispor", roleId: "TAKIMROLID_1", emoji: "🇹🇷" },
  { name: "Kocaelispor", roleId: "TAKIMROLID_2", emoji: "🇹🇷" },
  { name: "Sakaryaspor", roleId: "TAKIMROLID_3", emoji: "🇹🇷" },
  { name: "Göztepe", roleId: "TAKIMROLID_4", emoji: "🇹🇷" },
  { name: "Geosis Boluspor", roleId: "TAKIMROLID_5", emoji: "🇹🇷" },
  { name: "Bursaspor", roleId: "TAKIMROLID_6", emoji: "🇹🇷" },
  { name: "Teksüt Bandırmaspor", roleId: "TAKIMROLID_7", emoji: "🇹🇷" },
  { name: "Manisa FK", roleId: "TAKIMROLID_8", emoji: "🇹🇷" },
  { name: "MKE Ankaragücü", roleId: "TAKIMROLID_9", emoji: "🇹🇷" },
  { name: "TÜMOSAN Konyaspor", roleId: "TAKIMROLID_10", emoji: "🇹🇷" },
  { name: "Onvo Antalyaspor", roleId: "TAKIMROLID_11", emoji: "🇹🇷" },
  { name: "Adanaspor", roleId: "TAKIMROLID_12", emoji: "🇹🇷" },
  { name: "Bellona Kayserispor", roleId: "TAKIMROLID_13", emoji: "🇹🇷" },
  { name: "Motolüx 68 Aksarayspor", roleId: "TAKIMROLID_14", emoji: "🇹🇷" },
  { name: "Yeni Mersin İdmanyurdu", roleId: "TAKIMROLID_15", emoji: "🇹🇷" },
  { name: "Atakaş Hatayspor", roleId: "TAKIMROLID_16", emoji: "🇹🇷" },
  { name: "Çaykur Rizespor", roleId: "TAKIMROLID_17", emoji: "🇹🇷" },
  { name: "Erzurumspor FK", roleId: "TAKIMROLID_18", emoji: "🇹🇷" },
  { name: "Sivasspor", roleId: "TAKIMROLID_19", emoji: "🇹🇷" },
  { name: "Artı Değer Vanspor FK", roleId: "TAKIMROLID_20", emoji: "🇹🇷" },
  { name: "Karaman FK", roleId: "TAKIMROLID_21", emoji: "🇹🇷" },
  { name: "E Koleji Isparta 32 Spor", roleId: "TAKIMROLID_22", emoji: "🇹🇷" },
  { name: "GMG Kastamonuspor", roleId: "TAKIMROLID_23", emoji: "🇹🇷" },
  { name: "Arca Çorum FK", roleId: "TAKIMROLID_24", emoji: "🇹🇷" },
  { name: "Samsunspor", roleId: "TAKIMROLID_25", emoji: "🇹🇷" },
  { name: "Gaziantep FK", roleId: "TAKIMROLID_26", emoji: "🇹🇷" },
  { name: "Fitmens Gömlek Yeni Malatyaspor", roleId: "TAKIMROLID_27", emoji: "🇹🇷" },
  { name: "Kızılkaya Tarım Şanlıurfaspor", roleId: "TAKIMROLID_28", emoji: "🇹🇷" },
  { name: "Mardin 1969 Spor", roleId: "TAKIMROLID_29", emoji: "🇹🇷" },
  { name: "Çimentaş Elazığspor", roleId: "TAKIMROLID_30", emoji: "🇹🇷" },
  { name: "Anagold 24 Erzincanspor", roleId: "TAKIMROLID_31", emoji: "🇹🇷" },
  { name: "Muşspor", roleId: "TAKIMROLID_32", emoji: "🇹🇷" },
  { name: "TPAO Batman Petrolspor", roleId: "TAKIMROLID_33", emoji: "🇹🇷" },
  { name: "Alagöz Holding Iğdır Futbol Kulübü", roleId: "TAKIMROLID_34", emoji: "🇹🇷" },
  { name: "Uğur Okulları İstanbulspor", roleId: "TAKIMROLID_35", emoji: "🇹🇷" },
  { name: "Trabzonspor", roleId: "TAKIMROLID_36", emoji: "🇹🇷" },
  { name: "Sipay Bodrum FK", roleId: "TAKIMROLID_37", emoji: "🇹🇷" },
  { name: "Akedaş Epsaş Kahramanmaraş İstiklalspor", roleId: "TAKIMROLID_38", emoji: "🇹🇷" },
  { name: "Corendon Alanyaspor", roleId: "TAKIMROLID_39", emoji: "🇹🇷" },
  { name: "Adana Demirspor", roleId: "TAKIMROLID_40", emoji: "🇹🇷" },
  { name: "Gençlerbirliği", roleId: "TAKIMROLID_41", emoji: "🇹🇷" },
  { name: "Emre Gökdemir İnşaat Ankara Keçiörengücü", roleId: "TAKIMROLID_42", emoji: "🇹🇷" },
  { name: "Afyonspor", roleId: "TAKIMROLID_43", emoji: "🇹🇷" },
  { name: "Diyarbekirspor", roleId: "TAKIMROLID_44", emoji: "🇹🇷" },
  { name: "Giresunspor", roleId: "TAKIMROLID_45", emoji: "🇹🇷" },
  { name: "Kütahyaspor", roleId: "TAKIMROLID_46", emoji: "🇹🇷" },
  { name: "Düzce Cam Düzcespor", roleId: "TAKIMROLID_47", emoji: "🇹🇷" },
  { name: "Artvin Hopaspor", roleId: "TAKIMROLID_48", emoji: "🇹🇷" },
  { name: "Tokat Belediye Plevnespor", roleId: "TAKIMROLID_49", emoji: "🇹🇷" },
  { name: "Kırşehir Futbol SK", roleId: "TAKIMROLID_50", emoji: "🇹🇷" },
  { name: "Muğlaspor", roleId: "TAKIMROLID_51", emoji: "🇹🇷" },
  { name: "Balıkesirspor", roleId: "TAKIMROLID_52", emoji: "🇹🇷" },
  { name: "Yurt Et Amasyaspor Futbol Kulübü", roleId: "TAKIMROLID_53", emoji: "🇹🇷" },
  { name: "Uşakspor", roleId: "TAKIMROLID_54", emoji: "🇹🇷" },
  { name: "52 Orduspor", roleId: "TAKIMROLID_55", emoji: "🇹🇷" },
  { name: "Osmaniyespor FK", roleId: "TAKIMROLID_56", emoji: "🇹🇷" },
  { name: "Karabük İdman Yurdu", roleId: "TAKIMROLID_57", emoji: "🇹🇷" },
  { name: "KOLİBRİ Ağrı 1970 Spor", roleId: "TAKIMROLID_58", emoji: "🇹🇷" },
  { name: "Zonguldakspor FK", roleId: "TAKIMROLID_59", emoji: "🇹🇷" },
  { name: "Niğde Belediyesispor", roleId: "TAKIMROLID_60", emoji: "🇹🇷" },
  { name: "Edirnespor", roleId: "TAKIMROLID_61", emoji: "🇹🇷" }
]; 